version: '2.0'
services:
  helloworld:
    build: ./helloworld
  apache:
    build: ./apache
    ports:
    - "80:80"
    volumes:
    - .:/code
    - c_GM:/usr/local/apache2/htdocs/
    links:
    - helloworld
volumes:
  c_GM: {}

